apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZOybA/Xzt4cthLPAEFINm38EmYQRu0ri65RoKP1QSypoFa+9Ps2VSg==,iv:xB8MUDbB5DGgqcgi175ePM7BmDbUXdfNABaWFlfyKdk=,tag:sVG1abQNvnpYAYuPT+SxuQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:O3/GClH9FedWzKyV8LxE93vZoThfWuI7aonQ8Cq8CqOgeO1qPA2SCDkVZtE9skdrUrLy8eyrwvhdktje4A20We+eaaukYigIC+REHmZnAHSkKBT9kd3XhKBO+oREMHaKt8540UchAL7c3tf44itxcYNIreCmZ3WCD6JYV54Ki+vViv0KY6QVp7KG3rkAgVVNSPNBt8M65HFoS+U7BzEpd9tAkP/PbPBwgBx6iDGmPL1M3y+0S46C,iv:+CFg/28809ujDnaJVl4KHM5MVQu9u7ifMXzkoNuhz90=,tag:q9D/Q7NDU3IcphYusjohcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2K0tUaG1uRGhTcjcyeGpw
            dS9NNDZtMVA3YlN5ajRxbnVBMmVQdmVKZHpRCjVUUTQwS21JWSt2dzg2QkF3TGRh
            ZllYenk2SmozZVNUdFdkSWZOcnE5d28KLS0tIGExQzNaZmJVWDBRT3ZpdFhTSFoz
            cWgrcVN0NXJjcGlBR2gwMmZPZ2VuU3MKzdV61EZnkGIIBGOYcQdKPKau2U7PWNgC
            G/NLCTwKwx5twbKgWv96h4U7/v32uHhPh/kM/AukKS1bWtVW4oATeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T03:04:39Z"
    mac: ENC[AES256_GCM,data:10SbO4Pl+IdmtDIjKo7h3CbMYle4dE3pcJaOB6YLSM8VBnYQuokrdzTmPyrFn34IdqHTMYpccqu72yM8zb8gPlXKo5erM8vTFwXPF6KDMENRpZt1lJYmEjzLxltJTmPqDG1sB2skmM7ZNf9XWshpNcXyLbX6X7q8d5UNcBGzcmk=,iv:B0GqpzZf9VniKKXZeKw1fMd4f+76ak8cfkIIQS9VZ/k=,tag:BMufJ/WBTYUmQBTkNMEOdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
