apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:PC11fCWzs+Uoju+ue9cAKZ4YmNWVHOasu+3C6ukiGtjokOK7vDUWBg==,iv:OQm6SPQxr5QVgcwLPfMV7cqNJDfzZb+6NYemK5ep668=,tag:7eemuo7+to7nWwXTMi0fQw==,type:str]
    credentials.json: ENC[AES256_GCM,data:Iwa9Z8zLkd8a5UjSR+CqPEvKMJj36NYW43fGBzEcmG98vpBVQnSvb5vQcl8cHQdo4K57WqEHmO9Dxhs5UUe1F/lVLnDM8cFwEkPl9AqXUcQxANACuirUbMIZtIbj0A2FIh5Z8ov6TKC3/1R+o0MzKHXo5kFtbwDz0M1ZZ+LnHcIDJ/YfrveDSA39+7neFGhbvZmyOpeFS2rWbH6Iz3kICtFoNoPoafkLExQxSfZPQEyTBPrUwkLt,iv:RVlBIi9YRu/429L80RsPEtw7fGDmTFagNxSSoq/Tj7c=,tag:H+rQncwy8FtzJ7QX0upbuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRCtGZDVkZi9JektOeXFp
            SG1WemJFbTR0TVJmYzNLSG9wYnFTWW5qMWpvCkg3YWxVU2xORjFXbHB1dW50QkhH
            ZFFJWWxab2JMSnBNU1JkTkdlY00xR00KLS0tIEtJSm5GWDQwR2VpN0haaDJLZHdF
            S1lCeUpMbm03MFI1b1YxK3VPbTZUZ3cKwGr4UOzgoy/ZdiMAOQrCvP5zsR/vRDbG
            THGwHtJbUtf3gx+mM2jfQDAPqdgKJwneglHj2XljC8kJxvSfI5SLdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T03:21:49Z"
    mac: ENC[AES256_GCM,data:MyJWXml3Mu0vbLo0KLBYLnjQb1riOnfNqNLDIVticdhm3GASe91CL9AFQnNKYhtdOkLbfazWAroo8koEXOUxx/ooGmTdfwypuAhA5FQ6Wh6TZw6o0AJHm5RSSLmcPj+Qfo+rheJPZgOk40Nf9u60U12rcu5HonzSog7Tklwt/FY=,iv:DEEpj9693jJ/i7a5gV7NFmrbKJdasIQL6nk+68/y9uA=,tag:9otQLZWj3sIoHhKfDVkdgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
