apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Xm6LXGKz9Em+bGofN2eIXwuvYfWkXLI05pf48diG7gsvTqmlemgdmQ==,iv:rtN9q510+V1/xXjHu+P8DBGqEWTW78k/kq6qpxpvPvI=,tag:wTX7cenxppAkf4iuKhYanA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWTdWOEhWb3JLK2MwMk5o
            WE5neXZwaTR6aXlMSFJScW9rMGUveWZIdkhRCm01ZHBFb2cxRTZQUGJ4MlZISUJa
            VTByNUZTdWg4UHQ2angzVWpCdUw0QTAKLS0tIHFNZFhtbERnRDI5V0YxR1JBWFdC
            MDdkZ0pZOGZlTzJQdDNvMGhBdGp1ZW8KqbJJlQgYBzC40tsDsQDrZ7fs53NIMEqJ
            h+eeAiooXaODMs/XYVfAG0yHPzCX2NFs6lV5NOHmsHB+kngtVljG1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T02:40:35Z"
    mac: ENC[AES256_GCM,data:giagIR7uWmLXXtg9IGCwZdE8ls5E/52TEt7L7ENhEzU9fQH2UvRqH/anyDisRTrhwf0jvY4YH00huCJT7Nj4/ygi1qIx5IpAV58V2lZbpcWtfIYrvdQmEQMHsDRHpQOT0NNS3IqpMo5cuns8/uB0sAgwRq+EIRc7N3/m/89K+SY=,iv:nNg1aStxjMzZnU+F7BsBeLOWTLOVN3Egq2fS5sOaOMo=,tag:RFFecUQj/zMen9nmezi69Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
