apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:GHZIOqQgKMzZ0waKdSLNezocpt/e4DzOjHWVDKvKrLbErVxK8tA9jQ==,iv:u2ww7IqtgYbnmTQxEUp8XObEYGg0OVVylxhqJTg2dyU=,tag:NDHk015JBDXdSeA1V23h+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTDk3Ni9OcGx1TmpGbGg0
            VWJabjVRamQvbFNuQk53bmIvd05qYk9WU2w4ClVyQVpqODNLenlPMzlDdUZTRndE
            WGlDYXZWMnZxRnREcTFLc3RyT0pXamsKLS0tIFZuaDFhT1VTMzQ4cThOT2ZYRXl0
            RmZSSjZxbDl0NWlqVTR5dm1EUzNwaHcKkx+7bZygCA4BmRVq8hQ/rpJGdAFv+j9i
            sV4+KSlo7t44LlFSdsDTe+DcVohqwjPfWojAun7tp2p47VhufyGH3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T03:04:39Z"
    mac: ENC[AES256_GCM,data:rw1oFHAK0+IMMGwHaz5Mj49NE1+rtPQgSIszwD1eJN26DHk3OHR2fcs9MgNu6tX8IeG5RTxxHMwAwhmQECyspvkQcfjHYG+2Vqksn+GsIdbLYPPLDvXTkWqi1kAn/yut3Yns6dzyMXvH0bjAXOnDVB5T5v3Lij+F8apTo3Se/ic=,iv:fN0ge0a50eHnIx16cy8El1DdZbUhJo6gQyD/cFVlvfA=,tag:exnLsXzMT7kEnLx/bHuouw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
