apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6MNX9LESyRENpSB6E1an9+LKp4iJVJ4Bb85r46mPtiUwiQ7I9NeFZA==,iv:RGTe2hk6Vvv03CT3W/OO0nz48mxWRjf8eOY3RFEe2pE=,tag:02BokVkE7LyEg8k0vLBrtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aElkQnpmK01hVVU3Nkgr
            dWpYZkcwa2UzdE5yNjdvaE16TmdlN3dVUlcwCjBFTzVweWhMbWNncjhiRWlHeWJu
            SCtocTlKT05IZmFhLzA0RzNvaFZ5Sm8KLS0tIC9uQUh4OG5aWGtMamdvc1M4dTNp
            N0ppa0oxbHA0UUpzMzlaRUZFK3RIU0EKeX8FfDmlgKOdlpZq5AzyEls3Ao4wk4su
            mJzzfZ9D3C7YJp6G+S2vTCT6A+tUk6t2yDztFP/aDeQ3JDLuDTgPrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T03:20:51Z"
    mac: ENC[AES256_GCM,data:MLh4bvGtSwglFMhTR/Wb8xmZXXLlWIpTtW/fkL10E6PG6AGurrDf9bzYFUbhT8BGYm53DFkfaKjAwxpCv7G6edOJt0wFeNueiTFT1LjuDLU7IZAUQU/tq4WUXNbW8+O0YISyl7pVwJBmlbblQzQqWx+++gQveITt3/Wy/eJa6A4=,iv:cZuX0tA0AL8bSgoxoJo5WplcmvUsDxDthRjxuwFq9P0=,tag:ZQVkgGAzo3mZpcEnvDVHvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
