apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:hqR++Uzs02pWSXP3dl3hpngvM7D9iomyO+0xA26NpmfmcbgqXEjeH59FSqlHt3Er5fWc658mDd0a6x0zBolPR+cQOML7/D4wcU0Tyjtl3AEdNdU1mYG+VU2Asoy2WA==,iv:Iqrn6QyYyhbCLZC43Pm0q7Ze7oOx94hzzM+fx+8qvC0=,tag:pXHPltXeFFcZc9guJSt+1A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CdXSeiUjxZG1,iv:SGhWniEW5hRp2pV38cqfBzuxhrmESThgrCDzdqOWjYI=,tag:AvMhdWz++FaVtD0BTfKL9A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:7JlXIfSn7G7sPlU7PQ6ETyh/,iv:LH/mqxkufVtALLlMfiP/LuTMc3WCMpt2uy2+hPG9qug=,tag:SYojhkZCrNRLb+6+cTjCQg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Tgsio/nRtIINlDgJuFGSr4tlLeA3wTnPYrn+PMDM+Qo6s3V6ocZU0Q==,iv:16UVyKWdwRDH8Ex+1+fxeIffSLho+/5PDWfUsfP6i1Y=,tag:F6UbTLRfRJmg2XdcpvS/XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVWJyVVYwVDlVbDRyTk82
            T1p1cHdCbU9vckdkOWhSVWpETG1pTkVOY3pzCm8zZk9JRUo0YTZrMDBWbVMrNkxr
            Ymo1aGk4MWtVYXZqK3RFMTdxYkV4aU0KLS0tIEJocnB5aWxWNW9lMVNMeW9wRFda
            Y0pGMnpXdjQ3N3k5NW91OGtrNEVlb28KLX5orBXAWTwgMNJfqrjBmmlta86nNMN9
            3xH4ClJ55CVVeTMjprO+uVXVRNICU798Kfia5pl0cOeCmEKV/X/xkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T03:21:49Z"
    mac: ENC[AES256_GCM,data:nGabgLNkDLsyhNEEDBVHjc4uyOKwsZoncPBadnnR85RDrt8VfyW2SHGKdA/3vFTj53lZ8boki3RpDTtddZy7pTxIX0oBCoGSXyEJ7gGLsmTFw2RS06fnqFQTVXUytWg7bgd8Of7HGxFuVrDaqTJl4ez2rms8jD/Dv0wxkLGo7LI=,iv:GV58I70ilf90gsJucTt4r7cbFbL0+FH7TUSeWDoe9wY=,tag:+dRqiXW1j2VoChlThCxuQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
