apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Ks/ubalRe4HLxxNEo2cgUeUnMemwVTE10GbIieZU0Jk=,iv:jIdD62MPDRMXqBJ55FXfUPIoaLzTjxe2+wtx2buC/wE=,tag:o+wzd0gr4qCllqvzyo8Xyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRXNINHUrVndwdmZSeDBu
            UXlqZDc5Q0twYW9aVVVZZDVrUWJOR0x6TGdZCm5HN0NtUGRRNkJYRmVMYnh3RjR1
            OFRvVDBUTFliSWVYSlpWaWdUSWdZTG8KLS0tIHB1ZURZbVQ0TGw2QUpKZWZMNGVw
            SEhXdEEwUUdyTWVsYnhDR2YrbnkxeEEKT23l9TbD+g6YARBQMtqPa/qHbUOG+thN
            zBzubIDZjsGBjTcGI3kiKkVk022rl0jyajvKaEvma4eDN2/w5maAjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T02:40:35Z"
    mac: ENC[AES256_GCM,data:1Z57UZcdeuFb59HTPlctZ7c+UUaEWDw0BTDpgM5ur98DWlA3AsufJsZmZfcqX6YRAZj+8hN6zQeJ0/C3m1M8+awol0dsisw9omIRMQGaUOMeSqN2d8C1+pVAflmDN/9oWTZXa24BIuD/Fy4Ou/QenisaZE2eqrrTDcXPN080Jw0=,iv:q2bhasAMh8GwtzIoiSNwchL7MPRnhAIm9of9lRoJ7xM=,tag:HRGYfNhhW+LdaFK4cDbC7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
