apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UWGJtghV+Xq2OdHKsKN/JK0RldonvTwyNPvw47aMaBo=,iv:JI8vMklVH8y8tJvZ0342D2Tx3Ju7VSzM1wLlZ+Sd4DE=,tag:JqaqLduQa6UX6JSOE9Lf2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kkg5pt624664eej22kpa8lqzt6dumkmanfxlh0yp72yz28u4dvyq2l94wm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UmdCR08vWnlRRExLSEw2
            YXgrTk9Rd3JxNi80am5yYzVLcFZUanlUTWlzCmtoYkNBdzFha0lPOU9pN1BhdUd3
            LytzaGM4SXpuVm5NSEdkSHd4ZGNOcWcKLS0tIGFkeVVtOHdRVXdRTlZvUWwvVDY3
            ekpDZ2tIYWZ1dnI5SnVubGlGQW9NWEkKpbSDmXpRP284OhyFoU9T00VxaHsfegUI
            21GL77kv6/n/lUaOUsPTZUiIxO0PFfLT8Zi1UbWVDX0aex+BC3k8og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T03:04:39Z"
    mac: ENC[AES256_GCM,data:H5pX8CEUOmlX7x1cgqR2xNoLWQTN0nzuKJaiKspvrhI3XnEO0B63vq+f6QMMy91kAnJuvJaGYlChMItn/dpZ0SpxKsFJlKuRjoBwQj1Mw5PSSyjOY/DQcfBJrznhWLwnFbl3z1O9dMo/Ggw45O2rpHYeB3X5g1mIiPt5egAbozY=,iv:orRSnf7QgLIJLT0QB3Gm6jhVUNgY6FBf9qZib7XeqYI=,tag:STiPU/nviTmwjYq3V0ZObQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
